"""
Solution for problem #6 [Generated by avoe's afs.py]

Statement of the problem:
Rəqəmlərlə daxil edilmiş ədədi yazılı şəkildə çapa verən proqram.
"""

a = int(input())
alphabet_1 = {
    0: 'sıfır',
    1: 'bir',
    2: 'iki',
    3: 'üç',
    4: 'dört',
    5: 'beş',
    6: 'altı',
    7: 'yeddi',
    8: 'səkkiz',
    9: 'doqquz'
}
steps = ["yüz", "min", "milyon", "milyar", "trilyon", "katrilyon"]
