"""
Solution for problem #3 [Generated by avoe's afs.py]

Statement of the problem:
Klaviaturadan aralarında bir boşluq olmaqla daxil edilmiş sözlərdən ibarət olan sətrin hər bir sözünün tərkibində "w" hərfinin sayını çap edən proqramı Python dilində yazın.
"""

n = input()
k = n.split(' ')
lenghts = []
for i in k:
    lenghts.append(i.count('w'))
for i in range(len(lenghts)):
    print("Daxil edilmiş cümlənin " + str(i+1) + " saylı sözündə " + str(lenghts[i]) + " sayda w simvolu mövcuddur")
    
#* Completed