"""
Solution for problem #1 [Generated by avoe's afs.py]

Statement of the problem:
Klaviaturadan aralarında bir boşluq olmaqla bir stirdə istifadəçi parolları daxil etmişdir. Bu sətirdəki parollardan simvolları arasında rəqəm simvolu olmayanlarını silərək alınmış yeni sətri çapa verən proqram yazın.
"""

a = input()
list_a = a.split(' ')

for i in list_a:
    if '0' in i or '1' in i or '2' in i or '3' in i or '4' in i or '5' in i or '6' in i or '7' in i or '8' in i or '9' in i:
        print(i, end=' ')
print()