"""
Solution for problem #5 [Generated by avoe's afs.py]

Statement of the problem:
Daxil edilmiş natural ədədin hansı ən böyük 2-nin qüvvətinə bölündüyünü tapan proqram yazın.
"""

n = int(input())
k = 1
this = 0
while 2**k <= n:
    if n % 2**k == 0:
        this = 2**k
    k += 1
print(this)

#* Completed