"""
Solution for problem #4 [Generated by avoe's afs.py]

Statement of the problem:
Boşluqlarla daxil edilmiş sətirin hər sözünün son simvolunu həmin simvolun sözdəki sıra yeri ilə əvəz edən proqram yazın
"""

n = input()
k = n.split(' ')

#! Uncompleted